name: Integ tests with Remote Store
# This workflow is triggered on pull requests and pushes to main or an OpenSearch release branch
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
    # Job name
    name: Build and test Job-scheduler
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses the setup-java Github action: https://github.com/actions/setup-java
      - name: Set Up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: ${{ matrix.java }}
      # This step uses the checkout Github action: https://github.com/actions/checkout
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Run Job-scheduler Integ Tests with Remote Store
        run: |
          echo "Running integ tests with security..."
          ./gradlew :opensearch-job-scheduler-sample-extension:integTest --tests "*RestIT" -Dremote_store.enabled=true
